
import "./globals.css";


export const metadata = {
  title: "The Nexus Table",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=satoshi@400&display=swap" rel="stylesheet"></link>
        <link href="https://api.fontshare.com/v2/css?f[]=archivo@300,400,500&display=swap" rel="stylesheet"></link>
      </head>
      <body
        
        className={` antialiased  flex h-screen  flex-col justify-items-center pb-8 `}
      >
        <div className="fixed -z-20 backdrop-blur  w-full h-dvh flex justify-center items-center ">
          <div className="gradient backdrop-blur -z-10 w-full h-full p-20"></div>
        </div>
        {children}
        
      </body>
    </html>
  );
}
